- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: (ansible_facts | default({})).get('os_family', '') == "Debian"

- name: Install Debian baseline packages
  ansible.builtin.apt:
    name: "{{ common_packages_debian }}"
    state: present
  when: (ansible_facts | default({})).get('os_family', '') == "Debian"

- name: Install Fedora baseline packages
  ansible.builtin.dnf:
    name: "{{ common_packages_fedora }}"
    state: present
  when: (ansible_facts | default({})).get('distribution', '') == "Fedora"
