common_packages_debian:
  - curl
  - git
  - htop
  - jq
  - python3

common_packages_fedora:
  - curl
  - git
  - htop
  - jq
  - python3

ssh_authorized_keys_user: root
ssh_authorized_keys_base: []
ssh_authorized_keys_extra: []
