# Encrypt this file as vault.yml using ansible-vault.
#
# example:
# private_repo_deploy_key: |
#   -----BEGIN OPENSSH PRIVATE KEY-----
#   ...
#   -----END OPENSSH PRIVATE KEY-----
#
# frigate_env_content: |
#   MQTT_PASSWORD=...
#   OPENAI_API_KEY=...
#   GEMINI_API_KEY=...
